version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/bigbang-template
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Check Lints
          command: ./gradlew clean
              detektCheck
              detektFormat
              lint
              --max-workers=2
      - run:
          name: Assemble
          command: ./gradlew
              assemble
              assembleAndroidTest
               --max-workers=2
      - run:
          name: Run tests and checks
          command: ./gradlew build --max-workers=2
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
