version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/bigbang-template
    environment:
      GRADLE_OPTS: '-Dorg.gradle.parallel=false -Dorg.gradle.daemon=false'
      _JAVA_OPTIONS: "-Xmx1024m"
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean
              build
              assembleAndroidTest
      - run:
          name: Check Lints
          command: ./gradlew lint
              detektCheck
              detektFormat
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
